version: '3.8'

services:
  app:
    build: .
    container_name: nomina_validator_app
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./temp_uploads:/app/temp_uploads
      - ./logs:/app/logs
